package eteyecharles.com.bridgecollege;

import java.util.ArrayList;
import java.util.List;

import eteyecharles.com.bridgecollege.CourseModel;

public class DataProvider {


    private static List<CourseModel> data = new ArrayList<>();

    public static List<CourseModel> getData() {
        return data;

    }

    static {

        data.add(new CourseModel(10101, "Designing a Basic Digital Character I", "This course covers the creation of a basic, engaging character model, from concept development through sketching and modeling of the character. Students will be expected to research and pitch a design and background story, creating concept drawings, storyboards, animatics, and a traditional clay maquette. In the modeling portion of the course, you will construct a basic rig with 3D modeling tools, resulting in a fully animate-able character that can be skinned in any major 3D software package.", 3));

        data.add(new CourseModel(10102, "Designing a Basic Digital Character II", "Designing a Basic Digital Character II reviews basic character creation techniques and advances to character setup and final rendering. Learn to rig and skin the character skeleton to create smooth and expressive movement possible. Then, during rendering phase, you’ll learn to create custom textures and materials and apply these to create a realistic appearance for your model.", 3));

        data.add(new CourseModel(10103, "Animating in 2D with Adobe Flash", "Despite the prevalence of Maya and 3ds Max, Flash is still a huge player in the 2D animation world, being employed in shows from the cult phenomenon My Little Pony: Friendship is Magic and Looney Tunes to the full-length feature The Secret of Kells. This course shows you how to sketch a basic character, start drawing in Flash using vector shapes and paths, convert drawings to symbols, and animate a character along a timeline using keyframes and tweens. Then, you’ll learn how to publish to different formats, including SWF, and what the best distribution methods are for your movie in today’s media landscape.", 2));

        data.add(new CourseModel(10104, "Creating a Flash Game", "Browser-based gaming is a huge industry and developers are looking for animators that cannot only design, but code their own games. Creating a Flash Game shows Flash animators how to take their existing skills to the next level with an introduction to game theory and ActionScript. Dr. Neils Barclaymore walks students through the principles of solid game design and techniques that translate to directly to the storyboard. Then dive into ActionScript, an object-oriented language that is at once powerful and flexible. Students will leave the class with a sophisticated, fully-functioning game that engages users and inspires play.", 2));

        data.add(new CourseModel(20101, "Figure Drawing I", "Figure drawing is an invaluable tool for mastering the human form and postures. This course covers basic pose and composition, using pencil, charcoal, and ink. Each session will feature a unique model and include a combination of gesture drawing and longer sustained poses. The sessions conclude with a crit round, where each student receives individual attention and advice.", 3));

        data.add(new CourseModel(20102, "Figure Drawing II", "Students in our advanced figure painting course focus on producing one finished painting with a selected model of their choosing. Artists are mentored through the process of initial conception, lighting, posing, and composition. Due to the unique nature of this course, only a limited number of students are accepted and should be prepared to submit a portfolio of their work when applying to register.", 3));

        data.add(new CourseModel(20103, "Architectural Drawing: Drafting I", "Though most architectural drawing has migrated to CAD software, design firms still expect a strong foundational knowledge that comes with manual drafting. This course defines the conventions for documenting modern buildings, including viewpoint, scale, annotation, and cross-referencing. Students will create floor plan, site plan, elevation, and cross section views of structures, with a major emphasis on project presentation and a secondary emphasis on structural and service needs. The course will also touch on migrating to computer-aided design (CAD) software and the benefits of transitioning working drawings into a digital format.", 2));

        data.add(new CourseModel(30101, "Pattern Making", "Pattern making is the key to well-fitting pattern blocks and clothes, as well as the efficiency of garment manufacturing. In this course, you’ll learn to design clothing using one of three pattern making methods: flat-pattern using common slopers, custom pattern-making with French curves, and draping. After creating basic mockups, you’ll learn how to make variations on a simple design and finally, produce a finished garment. The course will also show how to integrate these methods with pattern-making software that, while still in its infancy, is capitalizing on the revolutions made with CAD software.", 3));

        data.add(new CourseModel(30102, "Garment Construction I", "Sewing is simple; constructing a beautifully tailored garment in multiple sizes is not. In this class, you’ll learn how to customize patterns, properly choose and cut fabric, how to choose needles, machines, and stiches, and the unique of fabrics such as wool, silk, cotton, and synthetics. You’ll discover how to perform sewing techniques such as darts, pleats, set-in sleeves, and more. This class is invaluable reference for both the budding fashion designers and the more seasoned tailors among us.", 3));

        data.add(new CourseModel(30103, "Garment Construction II", "This class takes up where the first installment leaves off and presents working with specialized fabrics (such as for evening and bridal wear), tailoring, fabric embellishments (buttons, embroidery, sequins, and more), and an introduction to textile technology. You’ll also review famed haute couture techniques and find out what makes a couture garment just so special. The class is design for the advanced sewer who has perfected the basics and wants to advance their career or interest in fashion.", 3));

        data.add(new CourseModel(30104, "Textile Design", "With the explosion in available synthetics, the garment industry has never-before-seen options and the consumer now wears lighter, more durable, and less expensive fabrics than ever before. These changes weren’t possible without the technology innovations made through textile design. Companies like L.L. Bean and Patagonia are hiring textile designers to create state-of-the-art fabrics that are breathable, provide protection from the elements (sun and snow), and are still colorful and fashion-conscious. This course explores current and past trends in fabrics, from texture and color to composition, the production cycle for most modern fabrics, how to paint and design compelling palettes and patterns, the process for creating woven and synthetic textiles, and how to market your designs.", 3));

        data.add(new CourseModel(40101, "Typography for Graphic Designers", "Graphic designers paint with color, line, and imagery, but they also paint with words—and choosing a font is just the beginning. In this course, you’ll learn how to personalize fonts by making adjustments to x-height, kerning and leading, weight, and size. You’ll also learn to play fonts against each other and harness the power of color to affect mood, emotion, and message, by learning about complementary and harmonic hues. This course will teach you how to think of type as necessary component of a great overall design, not merely text to be buried in its midst.", 3));

        data.add(new CourseModel(40102, "Principles of Interface Design & User Experience", "After years of general neglect, user interfaces—the portal through which we interact with software or are presented content on the Internet—are finally getting the attention they deserve. UI/UX design is a hot topic and graphic designers are being pulled in not only to make the experience aesthetically pleasing, but also as intelligent and as efficient as possible. The course teaches the principles and best practices behind good design, covering specifics such as navigation, icon design, menus, grouping, and error handling. Designers will also learn about the development process, from user analysis to prototyping and testing.", 3));

        data.add(new CourseModel(50101, "Music Theory & Ear Training", "At the foundation of all great music and musicians is  the understanding of the theories of harmony,  melodic practices, and analysis of music composition. Successful completion of this class will result in students having the basic understanding of rhythm, beat, standard notation, and composition instruments. Students will learn how to interpret story through music and how culture can shape an audience's perception of musical performances. At the beginning of this class, all students will be assessed for their unique skill set. This will be the basis for determining the individual achievement levels for ear training.", 3));

        data.add(new CourseModel(50102, "Music Production", "Music Production will allow students to explore the techniques that engineers, producers, and composers use to create audio recordings. They will also  learn the basics of recording, mixing, and editing audio for use in music and video formats. This course  will cover the basics of using midi equipment to enhance music productions.  Upon completion of the course students will be able to create a digital audio project from concept to finished product. Our state-of-the-art audio workstations will provide the environment to familiarize yourself with the most current tools and software to create your own masterpieces.", 2.5));

        data.add(new CourseModel(60101, "Photography Workshop I: Print", "The basic principles of photography create a solid foundation for photographers, whether they choose to compose their photos in print or digitally. In this course we'll take students through the basic concepts and teach methods for creating stunning photographs. Students will learn the rules of composition, functions of a SLR camera, usage of light, exposure, aperture, and shutter speeds. The instructor will also help students learn how to develop their portfolio and methods for distribution of their work. Students will be required to have a SLR camera with manual controls to complete this class.", 2));

        data.add(new CourseModel(60102, "Photography Workshop II: Digital", "This course will continue on the principles outlined in Photography Workshop I: Print. Students will learn about the unique options for digital photography and learn to understand the digital environments and how to work with them. Students will also learn about image resolution,  color modes, file management, image adjustments,  and editing and software tools. The course also introduces concepts for using web tools to create a digital portfolio for sharing work on the world wide web. This course also includes a workshop to introduce publishing options and learn methods for protecting, licensing, and distributing images.", 3));

        data.add(new CourseModel(60103, "Photography Hands On Assignment", "The majority of this class will take place outside of the classroom, with 5 lectures and check-in meetings throughout the course. Students will be given 4 photography projects, in both print and digital photography formats, to help them master the techniques of photography and prepare them for working on field assignments. The course also teaches students how to find contacts and get their work into the hands of industry professionals.", 5));

    }
}
